# This file was generated by GoReleaser. DO NOT EDIT.
cask "claudeos" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "41a7cb18ba9e87ef8474d49e8cb8737efef252e07c2860974ed0e53cc8d98a41"
      url "https://github.com/pablobfonseca/claudeos/releases/download/v#{version}/claudeos_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "20ea4324f9fe0af6735996ba7078d505135ff4db5d604ac91e4b6488a5b40a92"
      url "https://github.com/pablobfonseca/claudeos/releases/download/v#{version}/claudeos_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "claudeos"
  desc "Terminal command center for the Obsidian + Claude Code queue workflow: browse and mutate project queues, launch plan/implement sessions in tmux"
  homepage "https://github.com/pablobfonseca/claudeos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claudeos"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claudeos"]
    end
  end

  # No zap stanza required
end
