# This file was generated by GoReleaser. DO NOT EDIT.
cask "claudeos" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "961e227c90f127fa1e187ef5a7624df17dad8cbc0bf016755e70a0ff3fbe0c91"
      url "https://github.com/pablobfonseca/claudeos/releases/download/v#{version}/claudeos_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8409539e9f2956b63b2952e23839e51cdf5d5f3d2bb0a62f6cf7561e900c4a6"
      url "https://github.com/pablobfonseca/claudeos/releases/download/v#{version}/claudeos_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "claudeos"
  desc "Terminal command center for the Obsidian + Claude Code queue workflow: browse and mutate project queues, launch plan/implement sessions in tmux"
  homepage "https://github.com/pablobfonseca/claudeos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claudeos"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claudeos"]
    end
  end

  # No zap stanza required
end
