# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyactions" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b5c66adabcfc871eb48c5e97d2366dfe5813a504b4b22b7d249766ae0ae9fb0f"
      url "https://github.com/pablobfonseca/lazy-actions/releases/download/v#{version}/lazyactions_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de9ddb22000185b1a490d9a337c8d104ac3481fcc7a50065ff73472387a10ddd"
      url "https://github.com/pablobfonseca/lazy-actions/releases/download/v#{version}/lazyactions_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "lazyactions"
  desc "Bubble Tea TUI that watches GitHub Actions runs and sends desktop/mobile notifications"
  homepage "https://github.com/pablobfonseca/lazy-actions"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyactions"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyactions"]
    end
  end

  # No zap stanza required

end
