# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyactions" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "dee391484c2e8e25b236a0473becd7d04c17e08e28058359feafb89447733837"
      url "https://github.com/pablobfonseca/lazy-actions/releases/download/v#{version}/lazyactions_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "af11dfbb63dddb63c74300f36de0bd9f8551d22ac30c81c6d10aee26cba702de"
      url "https://github.com/pablobfonseca/lazy-actions/releases/download/v#{version}/lazyactions_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "lazyactions"
  desc "Bubble Tea TUI that watches GitHub Actions runs and sends desktop/mobile notifications"
  homepage "https://github.com/pablobfonseca/lazy-actions"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyactions"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyactions"]
    end
  end

  # No zap stanza required
end
