# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyactions" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "c7ea713062ce072aed6b4c8f1057d088bad00d2d8de1ba7754dcd1abe81130a8"
      url "https://github.com/pablobfonseca/lazy-actions/releases/download/v#{version}/lazyactions_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c475f0147fe124fd46f5a7fc0929e16161da49432c8027fffe5bd1a560f20157"
      url "https://github.com/pablobfonseca/lazy-actions/releases/download/v#{version}/lazyactions_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "lazyactions"
  desc "Bubble Tea TUI that watches GitHub Actions runs and sends desktop/mobile notifications"
  homepage "https://github.com/pablobfonseca/lazy-actions"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyactions"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/lazyactions"]
    end
  end

  # No zap stanza required
end
